'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="DATA_01")>  _
Partial Public Class LQ_SalesPersonListDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.MassarelliOutBoundOrders.My.MySettings.Default.DATA_01ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property VLQ_SalesPersonLists() As System.Data.Linq.Table(Of VLQ_SalesPersonList)
		Get
			Return Me.GetTable(Of VLQ_SalesPersonList)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.VLQ_SalesPersonList2012")>  _
Partial Public Class VLQ_SalesPersonList
	
	Private _slspsn_no As String
	
	Private _slspsn_name As String
	
	Private _email_addr As String
	
	Private _user_def_fld_1 As String
	
	Private _file_path_name As String
	
	Private _send As Boolean
	
	Private _save As Boolean
	
	Private _sent As Boolean
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_slspsn_no", DbType:="Char(3) NOT NULL", CanBeNull:=false)>  _
	Public Property slspsn_no() As String
		Get
			Return Me._slspsn_no
		End Get
		Set
			If (String.Equals(Me._slspsn_no, value) = false) Then
				Me._slspsn_no = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_slspsn_name", DbType:="Char(40)")>  _
	Public Property slspsn_name() As String
		Get
			Return Me._slspsn_name
		End Get
		Set
			If (String.Equals(Me._slspsn_name, value) = false) Then
				Me._slspsn_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_email_addr", DbType:="Char(40)")>  _
	Public Property email_addr() As String
		Get
			Return Me._email_addr
		End Get
		Set
			If (String.Equals(Me._email_addr, value) = false) Then
				Me._email_addr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_user_def_fld_1", DbType:="Char(30)")>  _
	Public Property user_def_fld_1() As String
		Get
			Return Me._user_def_fld_1
		End Get
		Set
			If (String.Equals(Me._user_def_fld_1, value) = false) Then
				Me._user_def_fld_1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_file_path_name", DbType:="Char(1000)")>  _
	Public Property file_path_name() As String
		Get
			Return Me._file_path_name
		End Get
		Set
			If (String.Equals(Me._file_path_name, value) = false) Then
				Me._file_path_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_send", DbType:="Int")>  _
	Public Property send() As Boolean
		Get
			Return Me._send
		End Get
		Set
			If ((Me._send = value)  _
						= false) Then
				Me._send = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_save", DbType:="Int")>  _
	Public Property save() As Boolean
		Get
			Return Me._save
		End Get
		Set
			If ((Me._save = value)  _
						= false) Then
				Me._save = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sent", DbType:="Int")>  _
	Public Property sent() As Boolean
		Get
			Return Me._sent
		End Get
		Set
			If ((Me._sent = value)  _
						= false) Then
				Me._sent = value
			End If
		End Set
	End Property
End Class
