'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BOOutBoundOrders.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCustomerNo.
        '''</summary>
        Friend ReadOnly Property Param_iCustomerNo() As String
            Get
                Return ResourceManager.GetString("Param_iCustomerNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iEndDate.
        '''</summary>
        Friend ReadOnly Property Param_iEndDate() As String
            Get
                Return ResourceManager.GetString("Param_iEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to igridcolname.
        '''</summary>
        Friend ReadOnly Property Param_iGridColName() As String
            Get
                Return ResourceManager.GetString("Param_iGridColName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to igridcolxml.
        '''</summary>
        Friend ReadOnly Property Param_iGridColXML() As String
            Get
                Return ResourceManager.GetString("Param_iGridColXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iInvoiceNo.
        '''</summary>
        Friend ReadOnly Property Param_iInvoiceNo() As String
            Get
                Return ResourceManager.GetString("Param_iInvoiceNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iOrderNo.
        '''</summary>
        Friend ReadOnly Property Param_iOrderNo() As String
            Get
                Return ResourceManager.GetString("Param_iOrderNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ipreset_type.
        '''</summary>
        Friend ReadOnly Property Param_iPresetType() As String
            Get
                Return ResourceManager.GetString("Param_iPresetType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iRecordState.
        '''</summary>
        Friend ReadOnly Property Param_iRecordState() As String
            Get
                Return ResourceManager.GetString("Param_iRecordState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iRepGroup.
        '''</summary>
        Friend ReadOnly Property Param_iRepGroup() As String
            Get
                Return ResourceManager.GetString("Param_iRepGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSalesRepNo.
        '''</summary>
        Friend ReadOnly Property Param_iSalesRepNo() As String
            Get
                Return ResourceManager.GetString("Param_iSalesRepNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSearchType.
        '''</summary>
        Friend ReadOnly Property Param_iSearchType() As String
            Get
                Return ResourceManager.GetString("Param_iSearchType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to islsrep_grp.
        '''</summary>
        Friend ReadOnly Property Param_iSlsrep_Grp() As String
            Get
                Return ResourceManager.GetString("Param_iSlsrep_Grp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iStartDate.
        '''</summary>
        Friend ReadOnly Property Param_iStartDate() As String
            Get
                Return ResourceManager.GetString("Param_iStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spoeGetOutboundOrders_Pending2012_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spoeGetOutboundOrders_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spoeGetOutboundOrders_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spoeGetOutboundOrders_History2012_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spoeGetOutboundOrdersHistory_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spoeGetOutboundOrdersHistory_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spoeSaveColLayout_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spoeSaveColLayout_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spoeSaveColLayout_MAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
